add BasicStructure
MarcRaeder/TypingPracticeReact pull request #1
Opened 2023-01-09 09:42 UTC by MarcRaeder

add Basic Structure

2023-01-11 12:39 UTC, matthiasdanne approved these changes

2023-01-11 12:39 UTC, matthiasdanne commented on my-app/src/Components/TypingArea.js
> +import { TextLengthInput } from "./TextLengtInput";
```suggestion
import { TextLengthInput } from "./TextLengthInput";
```

2023-01-16 08:33 UTC, stefanluth requested changes

2023-01-16 08:33 UTC, stefanluth commented on my-app/src/Components/Stats.js
> +}
import React :)

2023-01-16 08:33 UTC, stefanluth commented on my-app/src/Components/TextLengthInput.js
> +}
```suggestion
export function TextLengthInput(props) {
  return (
    <div class="TypingArea__TextLength">
      Text Length
      <input type="number" id="TextLength" onkeypress={props.handleKeyPress} placeholder="Text-Length 1-100" />
    </div>
  );
}
```

Use the props :)

2023-01-16 08:33 UTC, stefanluth commented on my-app/src/Components/TextLengthInput.js
> +}
I can't find the handleKeyPress function :o

2023-01-17 09:22 UTC, stefanluth requested changes

2023-01-17 09:22 UTC, stefanluth commented on my-app/src/Components/GenerateNewText.js
> +  // document.getElementById("btn").blur();
Remove comments :)

2023-01-17 09:22 UTC, stefanluth commented on my-app/src/Components/GenerateNewText.js
> +  const fehlermeldung = "Es sind nur 1 - 100 Wörter erlaubt";
```suggestion
  const errorMessage = "Es sind nur 1 - 100 Wörter erlaubt";
```

2023-01-17 09:22 UTC, stefanluth commented on my-app/src/Components/GenerateNewText.js
> +  let text = words.join(" ");
Use `const` :)

2023-01-17 09:22 UTC, stefanluth commented on my-app/src/Components/Stats.js
> +export function Stats(props) {
```suggestion
import React from "react";

export function Stats(props) {
```

2023-01-17 09:22 UTC, stefanluth commented on my-app/src/Components/TextLengthInput.js
> +export function TextLengthInput(props) {
```suggestion
import React from "react";

export function TextLengthInput(props) {
```

2023-01-17 09:22 UTC, stefanluth commented on my-app/src/Components/TypingArea.js
> +      <TypingField />
`TypingField` expects `props.text` :)

2023-01-17 09:22 UTC, stefanluth commented on my-app/src/index.js
> +root.render(TypingPractice());
```suggestion
root.render(<TypingPractice />);
```

2023-01-23 09:04 UTC, stefanluth approved these changes

2023-01-24 09:18 UTC, merged