Add generate new Text
MarcRaeder/TypingPracticeReact pull request #8
Opened 2023-01-24 14:53 UTC by MarcRaeder

2023-01-24 15:07 UTC, DevBastiS requested changes

2023-01-24 15:07 UTC, DevBastiS commented on my-app/src/Components/GenerateNewText.js
> +export async function GenerateNewText(textLength) {
You should stick to the 3 Layer Architecture here as well.
Meaning:

Create a Service and a Repository.
TextService and TextRepository.

The Repository is responsible for communicating with the API.
The Service handles Business Logic (nothing for this case I guess).

Create the Service and Repository and pass them as props to the component needing them.

2023-01-24 15:07 UTC, DevBastiS commented on my-app/src/Components/GenerateNewText.js
> +  let file = "https://random-word-api.herokuapp.com/word?number=" + textLength;
This should be the API you created in the previous assignment.

2023-01-25 09:11 UTC, DevBastiS requested changes

2023-01-25 09:11 UTC, DevBastiS commented on my-app/src/Service/TextService.js
> +    console.log(this.textRepository);
```suggestion
```

2023-01-25 09:11 UTC, DevBastiS commented on my-app/src/Components/TypingArea.js
> +    console.log(textService);
```suggestion
```

2023-01-25 09:11 UTC, DevBastiS commented on my-app/src/index.css
> +.TypingArea {
```suggestion
.typing-area {
```

Please adjust everywhere.

2023-01-25 09:11 UTC, DevBastiS commented on my-app/src/index.css
> +.TypingArea__Header {
```suggestion
.typing-area__header {
```

2023-01-25 09:11 UTC, DevBastiS commented on my-app/src/index.css
> +.test {
Remove if not needed.

2023-01-25 09:33 UTC, DevBastiS requested changes

2023-01-25 09:33 UTC, DevBastiS commented on my-app/src/index.css
> +.typing-area__textLength {
```suggestion
.typing-area__text-length {
```

2023-01-25 09:33 UTC, DevBastiS commented on my-app/src/index.css
> +.typing-area__buttonLine {
```suggestion
.typing-area__button-line {
```

2023-01-25 09:33 UTC, DevBastiS commented on my-app/src/index.css
> +.stats-area__buttonLine {
```suggestion
.stats-area__button-line {
```

2023-01-25 09:33 UTC, DevBastiS commented on my-app/src/index.css
> +.stats-area__dataButton {
```suggestion
.stats-area__data-button {
```

2023-01-25 09:33 UTC, DevBastiS commented on my-app/src/index.css
> +.stats-area__moreDetails {
```suggestion
.stats-area__more-details {
```

2023-01-25 09:40 UTC, DevBastiS approved these changes

2023-01-26 12:47 UTC, stefanluth approved these changes

2023-01-27 07:45 UTC, merged